version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - app/.env
    volumes:
      - .:/app

volumes:
  postgres_data:
